app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 60s
  api:
    git-hub-api-path: https://api.github.com
    stack-overflow-api-path: https://api.stackexchange.com
    bot-path: http://localhost:8090
  client-retry-type: constant
  kafka:
    bootstrap-server: localhost:9092
    topic-name: update-messages-topic
    partitions-count: 3
    replication-count: 1
  database-access-type: jpa
  useQueue: true

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - rate-limit-cache
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8080

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-cache
      url: /.*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getHeader('X-Forwarded-For')"
          bandwidths:
            - capacity: 3
              time: 10
              unit: seconds

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"