app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-path: "http://localhost:8080"
  client-retry-type: constant
  kafka:
    bootstrap-server: localhost:9092
    topic-name: update-messages-topic
    group-id: update
    partitions-count: 1
    replication-count: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"

management:
  server:
    port: 8091

  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    health:
      show-details: always